### ISSUE TITLE
Unexpected Behavior on Multidimensional Arrays

### ISSUE THREAD

**Issue by tathey1** [cfpark00/pyvoi#2]
I'm trying to understand the behavior of `VI` on multidimensional arrays.

For example this code:

```
import numpy as np 
import pyvoi

a = np.eye(2)
b = np.ones((2,2))
print(pyvoi.VI(a, b))
print(pyvoi.VI(a.flatten(), b.flatten()))
```

produces two different values (1.38 and 0.69). I believe the second is correct (under multiple interpretations), and I can't think of an interpretation where the first value is correct.

I believe the code improperly handles multidimensional arrays by, for example, using `len()` to find the size of an array [here](https://github.com/cfpark00/pyvoi/blob/d3b7ca5b929640331a5580983872361cf26f171d/pyvoi.py#L31) (which will be the length of the _first_ axis), but it uses `np.unique` to find unique values [here](https://github.com/cfpark00/pyvoi/blob/d3b7ca5b929640331a5580983872361cf26f171d/pyvoi.py#L35) (which involve flattening the array).

Assuming that class labels are scalar-valued, this could easily be fixed by flattening inputs before computing VI. Computing VI with respect to multi-dimensional labels is probably more complex. 

Happy to fix this if requested.

**Comment by cfpark00** [comment]
Yeah, lets add a flattening if the array is not 1d.

-Core

**Comment by tathey1** [comment]
merged PR flattens inputs before computuing VI. Closing this because the update should address our use cases (computing VI with respect to multi-dimensional labels does not seem to be a necessary feature).
